logs:
    - name: root
      level: info
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLogAppender
            file: root.txt
          - type: StdoutLogAppender
    - name: system
      level: debug
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLogAppender
            file: system.txt
            formatter: '%d%T[%p]%m%n'
          - type: StdoutLogAppender